import PDFDocument from "pdfkit";

export function generateAnalysisPDF(analysis, res) {
  const doc = new PDFDocument({
    margin: 50,
  });

  res.setHeader("Content-Type", "application/pdf");

  res.setHeader(
    "Content-Disposition",
    `attachment; filename="standardmatch-${analysis._id}.pdf"`
  );

  doc.pipe(res);

  // Title
  doc
    .fontSize(22)
    .text("StandardMatch Analysis Report", {
      align: "center",
    });

  doc.moveDown();

  // Basic information
  doc
    .fontSize(11)
    .text(`Analysis ID: ${analysis._id}`)
    .text(`Input Type: ${analysis.inputType}`)
    .text(`Filename: ${analysis.filename || "N/A"}`)
    .text(
      `Created At: ${analysis.createdAt?.toISOString() || "N/A"}`
    );

  doc.moveDown();

  doc
    .fontSize(14)
    .text("Extracted Text Preview");

  doc
    .fontSize(10)
    .text(analysis.extractedTextPreview || "N/A");

  doc.moveDown();

  doc
    .fontSize(16)
    .text("Recommended Indian Standards");

  doc.moveDown();

  analysis.recommendations.forEach((recommendation, index) => {
    doc
      .fontSize(13)
      .text(
        `${index + 1}. ${recommendation.standardNumber}`
      );

    doc
      .fontSize(11)
      .text(`Title: ${recommendation.title}`)
      .text(`Category: ${recommendation.category}`)
      .text(`Status: ${recommendation.status}`)
      .text(
        `Hybrid Score: ${recommendation.hybridScores.hybridScore}`
      );

    if (recommendation.keyClauses?.length) {
      doc.fontSize(11).text("Key Clauses:");

      recommendation.keyClauses.forEach((clause) => {
        doc.text(`• ${clause}`);
      });
    }

    if (recommendation.graphRelations?.normativeReferences?.length) {
      doc.text(
        `Normative References: ${recommendation.graphRelations.normativeReferences.join(
          ", "
        )}`
      );
    }

    if (recommendation.graphRelations?.testMethods?.length) {
      doc.text(
        `Test Methods: ${recommendation.graphRelations.testMethods.join(
          ", "
        )}`
      );
    }

    if (recommendation.graphRelations?.certifications?.length) {
      doc.text(
        `Certifications: ${recommendation.graphRelations.certifications.join(
          ", "
        )}`
      );
    }

    if (recommendation.graphRelations?.supersedes?.length) {
      doc.text(
        `Supersedes: ${recommendation.graphRelations.supersedes.join(
          ", "
        )}`
      );
    }

    if (recommendation.warnings?.length) {
      doc.text("Warnings:");

      recommendation.warnings.forEach((warning) => {
        doc.text(`• ${warning}`);
      });
    }

    if (recommendation.provenance) {
      doc.text(
        `Source: ${recommendation.provenance.type || "N/A"}`
      );

      doc.text(
        `Reference: ${
          recommendation.provenance.urlOrReference || "N/A"
        }`
      );

      doc.text(
        `Retrieved At: ${
          recommendation.provenance.retrievedAt || "N/A"
        }`
      );
    }

    doc.text(
      `Match Justification: ${
        recommendation.matchJustification || "N/A"
      }`
    );

    doc.moveDown();
  });

  doc
    .fontSize(9)
    .text(
      "Generated by StandardMatch.",
      {
        align: "center",
      }
    );

  doc.end();
}